name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push: #event
    branches:
      - main 
  pull_request:
    branches: 
      - main 

jobs:
  build:

    runs-on: ubuntu-latest  #container (jobs are running on the container)

    steps:
    # Step 1: Check out the code from the repository
    - name: Check out code 
      uses: actions/checkout@v2
    
    # Step 2: Set up Python environment
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        pip install pytest  # Ensure pytest is installed
        
    # Step 4: Run tests using pytest
    - name: Run tests 
      run: pytest
